name: Backend CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Code auschecken
              uses: actions/checkout@v4


            - name: Python 3.12 einrichten
              uses: actions/setup-python@v5
              with:
                   python-version: "3.12"
                   cache: "pip"

            - name: Dependencies installieren
              run: pip install -r requirements.txt && pip install httpx
        
    docker-build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Docker Image bauen
              run: docker build -t betgame-backend .